// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<S2Basin>>
abstract class S2Basin implements RustOpaqueInterface {
  Future<void> createOrReconfigureStream();

  Future<void> createStream();

  Future<void> deleteStream();

  Future<void> getStreamConfig();

  Future<void> listAllStreams();

  Future<void> reconfigureStream();
}
