// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'stream.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IBasin>>
abstract class IBasin implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<S2Basin>>
abstract class S2Basin implements RustOpaqueInterface {
  Future<void> createOrReconfigureStream();

  Future<void> createStream();

  Future<void> deleteStream();

  Future<void> getStreamConfig();

  Future<void> listAllStreams();

  Future<void> listStreams();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<S2Basin> newInstance({required IBasin basin}) =>
      RustLib.instance.api.crateBasinS2BasinNew(basin: basin);

  Future<void> reconfigureStream();

  Future<S2Stream> stream({required String name});
}
