// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<S2Client>>
abstract class S2Client implements RustOpaqueInterface {
  Future<void> basin();

  Future<void> createBasin();

  Future<void> deleteBasin();

  Future<void> getBasinConfig();

  Future<void> issueAccessToken();

  Future<void> listAccessTokens();

  Future<void> listAllAccessTokens();

  Future<void> listAllBasins();

  Future<void> listBasins();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<S2Client> newInstance({required ClientConfig config}) =>
      RustLib.instance.api.crateClientS2ClientNew(config: config);

  Future<void> reconfigureBasin();

  Future<void> revokeAccessToken();
}
