// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'append_session.dart';
import 'basin.dart';
import 'client.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'producer.dart';
import 'stream.dart';
import 'types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BatchSubmitTicketPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RecordSubmitTicketPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2AppendSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2BasinPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2ClientPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2ProducerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2StreamPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BatchSubmitTicket
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    dynamic raw,
  );

  @protected
  RecordSubmitTicket
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    dynamic raw,
  );

  @protected
  S2AppendSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    dynamic raw,
  );

  @protected
  S2Basin
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    dynamic raw,
  );

  @protected
  S2Client
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    dynamic raw,
  );

  @protected
  S2Producer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    dynamic raw,
  );

  @protected
  S2Stream
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    dynamic raw,
  );

  @protected
  S2AppendSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    dynamic raw,
  );

  @protected
  S2Basin
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    dynamic raw,
  );

  @protected
  S2Client
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    dynamic raw,
  );

  @protected
  S2Producer
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    dynamic raw,
  );

  @protected
  S2Stream
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    dynamic raw,
  );

  @protected
  BatchSubmitTicket
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    dynamic raw,
  );

  @protected
  RecordSubmitTicket
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    dynamic raw,
  );

  @protected
  S2AppendSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    dynamic raw,
  );

  @protected
  S2Basin
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    dynamic raw,
  );

  @protected
  S2Client
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    dynamic raw,
  );

  @protected
  S2Producer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    dynamic raw,
  );

  @protected
  S2Stream
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    dynamic raw,
  );

  @protected
  RustStreamSink<AccessTokenInfo> dco_decode_StreamSink_access_token_info_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<BasinInfo> dco_decode_StreamSink_basin_info_Sse(dynamic raw);

  @protected
  RustStreamSink<SequencedRecord> dco_decode_StreamSink_sequenced_record_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<StreamInfo> dco_decode_StreamSink_stream_info_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccessTokenInfo dco_decode_access_token_info(dynamic raw);

  @protected
  AccessTokenScope dco_decode_access_token_scope(dynamic raw);

  @protected
  AccessTokenScopeInput dco_decode_access_token_scope_input(dynamic raw);

  @protected
  AppendAck dco_decode_append_ack(dynamic raw);

  @protected
  AppendInput dco_decode_append_input(dynamic raw);

  @protected
  AppendRecord dco_decode_append_record(dynamic raw);

  @protected
  AppendRecordBatch dco_decode_append_record_batch(dynamic raw);

  @protected
  AppendRetryPolicy dco_decode_append_retry_policy(dynamic raw);

  @protected
  AppendSessionConfig dco_decode_append_session_config(dynamic raw);

  @protected
  BasinConfig dco_decode_basin_config(dynamic raw);

  @protected
  BasinInfo dco_decode_basin_info(dynamic raw);

  @protected
  BasinScope dco_decode_basin_scope(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppendInput dco_decode_box_autoadd_append_input(dynamic raw);

  @protected
  AppendRecord dco_decode_box_autoadd_append_record(dynamic raw);

  @protected
  AppendRetryPolicy dco_decode_box_autoadd_append_retry_policy(dynamic raw);

  @protected
  AppendSessionConfig dco_decode_box_autoadd_append_session_config(dynamic raw);

  @protected
  BasinConfig dco_decode_box_autoadd_basin_config(dynamic raw);

  @protected
  BasinScope dco_decode_box_autoadd_basin_scope(dynamic raw);

  @protected
  ClientConfig dco_decode_box_autoadd_client_config(dynamic raw);

  @protected
  Compression dco_decode_box_autoadd_compression(dynamic raw);

  @protected
  CreateBasinInput dco_decode_box_autoadd_create_basin_input(dynamic raw);

  @protected
  CreateStreamInput dco_decode_box_autoadd_create_stream_input(dynamic raw);

  @protected
  DeleteBasinInput dco_decode_box_autoadd_delete_basin_input(dynamic raw);

  @protected
  DeleteOnEmptyConfig dco_decode_box_autoadd_delete_on_empty_config(
    dynamic raw,
  );

  @protected
  DeleteStreamInput dco_decode_box_autoadd_delete_stream_input(dynamic raw);

  @protected
  IssueAccessTokenInput dco_decode_box_autoadd_issue_access_token_input(
    dynamic raw,
  );

  @protected
  ListAccessTokensInput dco_decode_box_autoadd_list_access_tokens_input(
    dynamic raw,
  );

  @protected
  ListAllAccessTokensInput dco_decode_box_autoadd_list_all_access_tokens_input(
    dynamic raw,
  );

  @protected
  ListAllBasinsInput dco_decode_box_autoadd_list_all_basins_input(dynamic raw);

  @protected
  ListAllStreamsInput dco_decode_box_autoadd_list_all_streams_input(
    dynamic raw,
  );

  @protected
  ListBasinsInput dco_decode_box_autoadd_list_basins_input(dynamic raw);

  @protected
  ListStreamsInput dco_decode_box_autoadd_list_streams_input(dynamic raw);

  @protected
  OperationGroupPermissions dco_decode_box_autoadd_operation_group_permissions(
    dynamic raw,
  );

  @protected
  ReadInput dco_decode_box_autoadd_read_input(dynamic raw);

  @protected
  ReadWritePermissions dco_decode_box_autoadd_read_write_permissions(
    dynamic raw,
  );

  @protected
  ReconfigureBasinInput dco_decode_box_autoadd_reconfigure_basin_input(
    dynamic raw,
  );

  @protected
  ResourceSet dco_decode_box_autoadd_resource_set(dynamic raw);

  @protected
  RetentionPolicy dco_decode_box_autoadd_retention_policy(dynamic raw);

  @protected
  RetryConfig dco_decode_box_autoadd_retry_config(dynamic raw);

  @protected
  StorageClass dco_decode_box_autoadd_storage_class(dynamic raw);

  @protected
  StreamConfig dco_decode_box_autoadd_stream_config(dynamic raw);

  @protected
  StreamPosition dco_decode_box_autoadd_stream_position(dynamic raw);

  @protected
  TimestampingConfig dco_decode_box_autoadd_timestamping_config(dynamic raw);

  @protected
  TimestampingMode dco_decode_box_autoadd_timestamping_mode(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  ClientConfig dco_decode_client_config(dynamic raw);

  @protected
  Compression dco_decode_compression(dynamic raw);

  @protected
  CreateBasinInput dco_decode_create_basin_input(dynamic raw);

  @protected
  CreateStreamInput dco_decode_create_stream_input(dynamic raw);

  @protected
  DeleteBasinInput dco_decode_delete_basin_input(dynamic raw);

  @protected
  DeleteOnEmptyConfig dco_decode_delete_on_empty_config(dynamic raw);

  @protected
  DeleteStreamInput dco_decode_delete_stream_input(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IndexedAppendAck dco_decode_indexed_append_ack(dynamic raw);

  @protected
  IssueAccessTokenInput dco_decode_issue_access_token_input(dynamic raw);

  @protected
  List<AccessTokenInfo> dco_decode_list_access_token_info(dynamic raw);

  @protected
  ListAccessTokensInput dco_decode_list_access_tokens_input(dynamic raw);

  @protected
  ListAllAccessTokensInput dco_decode_list_all_access_tokens_input(dynamic raw);

  @protected
  ListAllBasinsInput dco_decode_list_all_basins_input(dynamic raw);

  @protected
  ListAllStreamsInput dco_decode_list_all_streams_input(dynamic raw);

  @protected
  List<AppendRecord> dco_decode_list_append_record(dynamic raw);

  @protected
  List<BasinInfo> dco_decode_list_basin_info(dynamic raw);

  @protected
  ListBasinsInput dco_decode_list_basins_input(dynamic raw);

  @protected
  List<Operation> dco_decode_list_operation(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(Uint8List, Uint8List)>
  dco_decode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SequencedRecord> dco_decode_list_sequenced_record(dynamic raw);

  @protected
  List<StreamInfo> dco_decode_list_stream_info(dynamic raw);

  @protected
  ListStreamsInput dco_decode_list_streams_input(dynamic raw);

  @protected
  Operation dco_decode_operation(dynamic raw);

  @protected
  OperationGroupPermissions dco_decode_operation_group_permissions(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AppendRetryPolicy? dco_decode_opt_box_autoadd_append_retry_policy(
    dynamic raw,
  );

  @protected
  BasinConfig? dco_decode_opt_box_autoadd_basin_config(dynamic raw);

  @protected
  BasinScope? dco_decode_opt_box_autoadd_basin_scope(dynamic raw);

  @protected
  Compression? dco_decode_opt_box_autoadd_compression(dynamic raw);

  @protected
  DeleteOnEmptyConfig? dco_decode_opt_box_autoadd_delete_on_empty_config(
    dynamic raw,
  );

  @protected
  OperationGroupPermissions?
  dco_decode_opt_box_autoadd_operation_group_permissions(dynamic raw);

  @protected
  ReadWritePermissions? dco_decode_opt_box_autoadd_read_write_permissions(
    dynamic raw,
  );

  @protected
  ResourceSet? dco_decode_opt_box_autoadd_resource_set(dynamic raw);

  @protected
  RetentionPolicy? dco_decode_opt_box_autoadd_retention_policy(dynamic raw);

  @protected
  RetryConfig? dco_decode_opt_box_autoadd_retry_config(dynamic raw);

  @protected
  StorageClass? dco_decode_opt_box_autoadd_storage_class(dynamic raw);

  @protected
  StreamConfig? dco_decode_opt_box_autoadd_stream_config(dynamic raw);

  @protected
  StreamPosition? dco_decode_opt_box_autoadd_stream_position(dynamic raw);

  @protected
  TimestampingConfig? dco_decode_opt_box_autoadd_timestamping_config(
    dynamic raw,
  );

  @protected
  TimestampingMode? dco_decode_opt_box_autoadd_timestamping_mode(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  PageOfAccessTokenInfo dco_decode_page_of_access_token_info(dynamic raw);

  @protected
  PageOfBasinInfo dco_decode_page_of_basin_info(dynamic raw);

  @protected
  PageOfStreamInfo dco_decode_page_of_stream_info(dynamic raw);

  @protected
  ReadBatch dco_decode_read_batch(dynamic raw);

  @protected
  ReadFrom dco_decode_read_from(dynamic raw);

  @protected
  ReadInput dco_decode_read_input(dynamic raw);

  @protected
  ReadLimits dco_decode_read_limits(dynamic raw);

  @protected
  ReadStart dco_decode_read_start(dynamic raw);

  @protected
  ReadStop dco_decode_read_stop(dynamic raw);

  @protected
  ReadWritePermissions dco_decode_read_write_permissions(dynamic raw);

  @protected
  ReconfigureBasinInput dco_decode_reconfigure_basin_input(dynamic raw);

  @protected
  (Uint8List, Uint8List)
  dco_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(dynamic raw);

  @protected
  ResourceSet dco_decode_resource_set(dynamic raw);

  @protected
  RetentionPolicy dco_decode_retention_policy(dynamic raw);

  @protected
  RetryConfig dco_decode_retry_config(dynamic raw);

  @protected
  S2Error dco_decode_s_2_error(dynamic raw);

  @protected
  SequencedRecord dco_decode_sequenced_record(dynamic raw);

  @protected
  StorageClass dco_decode_storage_class(dynamic raw);

  @protected
  StreamConfig dco_decode_stream_config(dynamic raw);

  @protected
  StreamInfo dco_decode_stream_info(dynamic raw);

  @protected
  StreamPosition dco_decode_stream_position(dynamic raw);

  @protected
  TimestampingConfig dco_decode_timestamping_config(dynamic raw);

  @protected
  TimestampingMode dco_decode_timestamping_mode(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BatchSubmitTicket
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    SseDeserializer deserializer,
  );

  @protected
  RecordSubmitTicket
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    SseDeserializer deserializer,
  );

  @protected
  S2AppendSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    SseDeserializer deserializer,
  );

  @protected
  S2Basin
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    SseDeserializer deserializer,
  );

  @protected
  S2Client
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    SseDeserializer deserializer,
  );

  @protected
  S2Producer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    SseDeserializer deserializer,
  );

  @protected
  S2Stream
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    SseDeserializer deserializer,
  );

  @protected
  S2AppendSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    SseDeserializer deserializer,
  );

  @protected
  S2Basin
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    SseDeserializer deserializer,
  );

  @protected
  S2Client
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    SseDeserializer deserializer,
  );

  @protected
  S2Producer
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    SseDeserializer deserializer,
  );

  @protected
  S2Stream
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    SseDeserializer deserializer,
  );

  @protected
  BatchSubmitTicket
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    SseDeserializer deserializer,
  );

  @protected
  RecordSubmitTicket
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    SseDeserializer deserializer,
  );

  @protected
  S2AppendSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    SseDeserializer deserializer,
  );

  @protected
  S2Basin
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    SseDeserializer deserializer,
  );

  @protected
  S2Client
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    SseDeserializer deserializer,
  );

  @protected
  S2Producer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    SseDeserializer deserializer,
  );

  @protected
  S2Stream
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AccessTokenInfo> sse_decode_StreamSink_access_token_info_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BasinInfo> sse_decode_StreamSink_basin_info_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SequencedRecord> sse_decode_StreamSink_sequenced_record_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<StreamInfo> sse_decode_StreamSink_stream_info_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccessTokenInfo sse_decode_access_token_info(SseDeserializer deserializer);

  @protected
  AccessTokenScope sse_decode_access_token_scope(SseDeserializer deserializer);

  @protected
  AccessTokenScopeInput sse_decode_access_token_scope_input(
    SseDeserializer deserializer,
  );

  @protected
  AppendAck sse_decode_append_ack(SseDeserializer deserializer);

  @protected
  AppendInput sse_decode_append_input(SseDeserializer deserializer);

  @protected
  AppendRecord sse_decode_append_record(SseDeserializer deserializer);

  @protected
  AppendRecordBatch sse_decode_append_record_batch(
    SseDeserializer deserializer,
  );

  @protected
  AppendRetryPolicy sse_decode_append_retry_policy(
    SseDeserializer deserializer,
  );

  @protected
  AppendSessionConfig sse_decode_append_session_config(
    SseDeserializer deserializer,
  );

  @protected
  BasinConfig sse_decode_basin_config(SseDeserializer deserializer);

  @protected
  BasinInfo sse_decode_basin_info(SseDeserializer deserializer);

  @protected
  BasinScope sse_decode_basin_scope(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppendInput sse_decode_box_autoadd_append_input(SseDeserializer deserializer);

  @protected
  AppendRecord sse_decode_box_autoadd_append_record(
    SseDeserializer deserializer,
  );

  @protected
  AppendRetryPolicy sse_decode_box_autoadd_append_retry_policy(
    SseDeserializer deserializer,
  );

  @protected
  AppendSessionConfig sse_decode_box_autoadd_append_session_config(
    SseDeserializer deserializer,
  );

  @protected
  BasinConfig sse_decode_box_autoadd_basin_config(SseDeserializer deserializer);

  @protected
  BasinScope sse_decode_box_autoadd_basin_scope(SseDeserializer deserializer);

  @protected
  ClientConfig sse_decode_box_autoadd_client_config(
    SseDeserializer deserializer,
  );

  @protected
  Compression sse_decode_box_autoadd_compression(SseDeserializer deserializer);

  @protected
  CreateBasinInput sse_decode_box_autoadd_create_basin_input(
    SseDeserializer deserializer,
  );

  @protected
  CreateStreamInput sse_decode_box_autoadd_create_stream_input(
    SseDeserializer deserializer,
  );

  @protected
  DeleteBasinInput sse_decode_box_autoadd_delete_basin_input(
    SseDeserializer deserializer,
  );

  @protected
  DeleteOnEmptyConfig sse_decode_box_autoadd_delete_on_empty_config(
    SseDeserializer deserializer,
  );

  @protected
  DeleteStreamInput sse_decode_box_autoadd_delete_stream_input(
    SseDeserializer deserializer,
  );

  @protected
  IssueAccessTokenInput sse_decode_box_autoadd_issue_access_token_input(
    SseDeserializer deserializer,
  );

  @protected
  ListAccessTokensInput sse_decode_box_autoadd_list_access_tokens_input(
    SseDeserializer deserializer,
  );

  @protected
  ListAllAccessTokensInput sse_decode_box_autoadd_list_all_access_tokens_input(
    SseDeserializer deserializer,
  );

  @protected
  ListAllBasinsInput sse_decode_box_autoadd_list_all_basins_input(
    SseDeserializer deserializer,
  );

  @protected
  ListAllStreamsInput sse_decode_box_autoadd_list_all_streams_input(
    SseDeserializer deserializer,
  );

  @protected
  ListBasinsInput sse_decode_box_autoadd_list_basins_input(
    SseDeserializer deserializer,
  );

  @protected
  ListStreamsInput sse_decode_box_autoadd_list_streams_input(
    SseDeserializer deserializer,
  );

  @protected
  OperationGroupPermissions sse_decode_box_autoadd_operation_group_permissions(
    SseDeserializer deserializer,
  );

  @protected
  ReadInput sse_decode_box_autoadd_read_input(SseDeserializer deserializer);

  @protected
  ReadWritePermissions sse_decode_box_autoadd_read_write_permissions(
    SseDeserializer deserializer,
  );

  @protected
  ReconfigureBasinInput sse_decode_box_autoadd_reconfigure_basin_input(
    SseDeserializer deserializer,
  );

  @protected
  ResourceSet sse_decode_box_autoadd_resource_set(SseDeserializer deserializer);

  @protected
  RetentionPolicy sse_decode_box_autoadd_retention_policy(
    SseDeserializer deserializer,
  );

  @protected
  RetryConfig sse_decode_box_autoadd_retry_config(SseDeserializer deserializer);

  @protected
  StorageClass sse_decode_box_autoadd_storage_class(
    SseDeserializer deserializer,
  );

  @protected
  StreamConfig sse_decode_box_autoadd_stream_config(
    SseDeserializer deserializer,
  );

  @protected
  StreamPosition sse_decode_box_autoadd_stream_position(
    SseDeserializer deserializer,
  );

  @protected
  TimestampingConfig sse_decode_box_autoadd_timestamping_config(
    SseDeserializer deserializer,
  );

  @protected
  TimestampingMode sse_decode_box_autoadd_timestamping_mode(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  ClientConfig sse_decode_client_config(SseDeserializer deserializer);

  @protected
  Compression sse_decode_compression(SseDeserializer deserializer);

  @protected
  CreateBasinInput sse_decode_create_basin_input(SseDeserializer deserializer);

  @protected
  CreateStreamInput sse_decode_create_stream_input(
    SseDeserializer deserializer,
  );

  @protected
  DeleteBasinInput sse_decode_delete_basin_input(SseDeserializer deserializer);

  @protected
  DeleteOnEmptyConfig sse_decode_delete_on_empty_config(
    SseDeserializer deserializer,
  );

  @protected
  DeleteStreamInput sse_decode_delete_stream_input(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IndexedAppendAck sse_decode_indexed_append_ack(SseDeserializer deserializer);

  @protected
  IssueAccessTokenInput sse_decode_issue_access_token_input(
    SseDeserializer deserializer,
  );

  @protected
  List<AccessTokenInfo> sse_decode_list_access_token_info(
    SseDeserializer deserializer,
  );

  @protected
  ListAccessTokensInput sse_decode_list_access_tokens_input(
    SseDeserializer deserializer,
  );

  @protected
  ListAllAccessTokensInput sse_decode_list_all_access_tokens_input(
    SseDeserializer deserializer,
  );

  @protected
  ListAllBasinsInput sse_decode_list_all_basins_input(
    SseDeserializer deserializer,
  );

  @protected
  ListAllStreamsInput sse_decode_list_all_streams_input(
    SseDeserializer deserializer,
  );

  @protected
  List<AppendRecord> sse_decode_list_append_record(
    SseDeserializer deserializer,
  );

  @protected
  List<BasinInfo> sse_decode_list_basin_info(SseDeserializer deserializer);

  @protected
  ListBasinsInput sse_decode_list_basins_input(SseDeserializer deserializer);

  @protected
  List<Operation> sse_decode_list_operation(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(Uint8List, Uint8List)>
  sse_decode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<SequencedRecord> sse_decode_list_sequenced_record(
    SseDeserializer deserializer,
  );

  @protected
  List<StreamInfo> sse_decode_list_stream_info(SseDeserializer deserializer);

  @protected
  ListStreamsInput sse_decode_list_streams_input(SseDeserializer deserializer);

  @protected
  Operation sse_decode_operation(SseDeserializer deserializer);

  @protected
  OperationGroupPermissions sse_decode_operation_group_permissions(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AppendRetryPolicy? sse_decode_opt_box_autoadd_append_retry_policy(
    SseDeserializer deserializer,
  );

  @protected
  BasinConfig? sse_decode_opt_box_autoadd_basin_config(
    SseDeserializer deserializer,
  );

  @protected
  BasinScope? sse_decode_opt_box_autoadd_basin_scope(
    SseDeserializer deserializer,
  );

  @protected
  Compression? sse_decode_opt_box_autoadd_compression(
    SseDeserializer deserializer,
  );

  @protected
  DeleteOnEmptyConfig? sse_decode_opt_box_autoadd_delete_on_empty_config(
    SseDeserializer deserializer,
  );

  @protected
  OperationGroupPermissions?
  sse_decode_opt_box_autoadd_operation_group_permissions(
    SseDeserializer deserializer,
  );

  @protected
  ReadWritePermissions? sse_decode_opt_box_autoadd_read_write_permissions(
    SseDeserializer deserializer,
  );

  @protected
  ResourceSet? sse_decode_opt_box_autoadd_resource_set(
    SseDeserializer deserializer,
  );

  @protected
  RetentionPolicy? sse_decode_opt_box_autoadd_retention_policy(
    SseDeserializer deserializer,
  );

  @protected
  RetryConfig? sse_decode_opt_box_autoadd_retry_config(
    SseDeserializer deserializer,
  );

  @protected
  StorageClass? sse_decode_opt_box_autoadd_storage_class(
    SseDeserializer deserializer,
  );

  @protected
  StreamConfig? sse_decode_opt_box_autoadd_stream_config(
    SseDeserializer deserializer,
  );

  @protected
  StreamPosition? sse_decode_opt_box_autoadd_stream_position(
    SseDeserializer deserializer,
  );

  @protected
  TimestampingConfig? sse_decode_opt_box_autoadd_timestamping_config(
    SseDeserializer deserializer,
  );

  @protected
  TimestampingMode? sse_decode_opt_box_autoadd_timestamping_mode(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  PageOfAccessTokenInfo sse_decode_page_of_access_token_info(
    SseDeserializer deserializer,
  );

  @protected
  PageOfBasinInfo sse_decode_page_of_basin_info(SseDeserializer deserializer);

  @protected
  PageOfStreamInfo sse_decode_page_of_stream_info(SseDeserializer deserializer);

  @protected
  ReadBatch sse_decode_read_batch(SseDeserializer deserializer);

  @protected
  ReadFrom sse_decode_read_from(SseDeserializer deserializer);

  @protected
  ReadInput sse_decode_read_input(SseDeserializer deserializer);

  @protected
  ReadLimits sse_decode_read_limits(SseDeserializer deserializer);

  @protected
  ReadStart sse_decode_read_start(SseDeserializer deserializer);

  @protected
  ReadStop sse_decode_read_stop(SseDeserializer deserializer);

  @protected
  ReadWritePermissions sse_decode_read_write_permissions(
    SseDeserializer deserializer,
  );

  @protected
  ReconfigureBasinInput sse_decode_reconfigure_basin_input(
    SseDeserializer deserializer,
  );

  @protected
  (Uint8List, Uint8List)
  sse_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  ResourceSet sse_decode_resource_set(SseDeserializer deserializer);

  @protected
  RetentionPolicy sse_decode_retention_policy(SseDeserializer deserializer);

  @protected
  RetryConfig sse_decode_retry_config(SseDeserializer deserializer);

  @protected
  S2Error sse_decode_s_2_error(SseDeserializer deserializer);

  @protected
  SequencedRecord sse_decode_sequenced_record(SseDeserializer deserializer);

  @protected
  StorageClass sse_decode_storage_class(SseDeserializer deserializer);

  @protected
  StreamConfig sse_decode_stream_config(SseDeserializer deserializer);

  @protected
  StreamInfo sse_decode_stream_info(SseDeserializer deserializer);

  @protected
  StreamPosition sse_decode_stream_position(SseDeserializer deserializer);

  @protected
  TimestampingConfig sse_decode_timestamping_config(
    SseDeserializer deserializer,
  );

  @protected
  TimestampingMode sse_decode_timestamping_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    BatchSubmitTicket self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    RecordSubmitTicket self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    S2AppendSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    S2Basin self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    S2Client self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    S2Producer self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    S2Stream self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    S2AppendSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    S2Basin self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    S2Client self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    S2Producer self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    S2Stream self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    BatchSubmitTicket self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    RecordSubmitTicket self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    S2AppendSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    S2Basin self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    S2Client self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    S2Producer self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    S2Stream self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_access_token_info_Sse(
    RustStreamSink<AccessTokenInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_basin_info_Sse(
    RustStreamSink<BasinInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sequenced_record_Sse(
    RustStreamSink<SequencedRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_stream_info_Sse(
    RustStreamSink<StreamInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_access_token_info(
    AccessTokenInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_access_token_scope(
    AccessTokenScope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_access_token_scope_input(
    AccessTokenScopeInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_append_ack(AppendAck self, SseSerializer serializer);

  @protected
  void sse_encode_append_input(AppendInput self, SseSerializer serializer);

  @protected
  void sse_encode_append_record(AppendRecord self, SseSerializer serializer);

  @protected
  void sse_encode_append_record_batch(
    AppendRecordBatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_append_retry_policy(
    AppendRetryPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_append_session_config(
    AppendSessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_basin_config(BasinConfig self, SseSerializer serializer);

  @protected
  void sse_encode_basin_info(BasinInfo self, SseSerializer serializer);

  @protected
  void sse_encode_basin_scope(BasinScope self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_append_input(
    AppendInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_append_record(
    AppendRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_append_retry_policy(
    AppendRetryPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_append_session_config(
    AppendSessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_basin_config(
    BasinConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_basin_scope(
    BasinScope self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_client_config(
    ClientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_compression(
    Compression self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_basin_input(
    CreateBasinInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_stream_input(
    CreateStreamInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_basin_input(
    DeleteBasinInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_on_empty_config(
    DeleteOnEmptyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_delete_stream_input(
    DeleteStreamInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_issue_access_token_input(
    IssueAccessTokenInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_access_tokens_input(
    ListAccessTokensInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_all_access_tokens_input(
    ListAllAccessTokensInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_all_basins_input(
    ListAllBasinsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_all_streams_input(
    ListAllStreamsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_basins_input(
    ListBasinsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_list_streams_input(
    ListStreamsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_operation_group_permissions(
    OperationGroupPermissions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_read_input(
    ReadInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_read_write_permissions(
    ReadWritePermissions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reconfigure_basin_input(
    ReconfigureBasinInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resource_set(
    ResourceSet self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_retention_policy(
    RetentionPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_retry_config(
    RetryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_storage_class(
    StorageClass self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stream_config(
    StreamConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stream_position(
    StreamPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_timestamping_config(
    TimestampingConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_timestamping_mode(
    TimestampingMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_client_config(ClientConfig self, SseSerializer serializer);

  @protected
  void sse_encode_compression(Compression self, SseSerializer serializer);

  @protected
  void sse_encode_create_basin_input(
    CreateBasinInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_stream_input(
    CreateStreamInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_basin_input(
    DeleteBasinInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_on_empty_config(
    DeleteOnEmptyConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_stream_input(
    DeleteStreamInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_indexed_append_ack(
    IndexedAppendAck self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_issue_access_token_input(
    IssueAccessTokenInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_access_token_info(
    List<AccessTokenInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_access_tokens_input(
    ListAccessTokensInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_all_access_tokens_input(
    ListAllAccessTokensInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_all_basins_input(
    ListAllBasinsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_all_streams_input(
    ListAllStreamsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_append_record(
    List<AppendRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_basin_info(
    List<BasinInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_basins_input(
    ListBasinsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_operation(
    List<Operation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(
    List<(Uint8List, Uint8List)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sequenced_record(
    List<SequencedRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stream_info(
    List<StreamInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_streams_input(
    ListStreamsInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_operation(Operation self, SseSerializer serializer);

  @protected
  void sse_encode_operation_group_permissions(
    OperationGroupPermissions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_append_retry_policy(
    AppendRetryPolicy? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_basin_config(
    BasinConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_basin_scope(
    BasinScope? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_compression(
    Compression? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_delete_on_empty_config(
    DeleteOnEmptyConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_operation_group_permissions(
    OperationGroupPermissions? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_read_write_permissions(
    ReadWritePermissions? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_resource_set(
    ResourceSet? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_retention_policy(
    RetentionPolicy? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_retry_config(
    RetryConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_storage_class(
    StorageClass? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stream_config(
    StreamConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stream_position(
    StreamPosition? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_timestamping_config(
    TimestampingConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_timestamping_mode(
    TimestampingMode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_page_of_access_token_info(
    PageOfAccessTokenInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_of_basin_info(
    PageOfBasinInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_page_of_stream_info(
    PageOfStreamInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_read_batch(ReadBatch self, SseSerializer serializer);

  @protected
  void sse_encode_read_from(ReadFrom self, SseSerializer serializer);

  @protected
  void sse_encode_read_input(ReadInput self, SseSerializer serializer);

  @protected
  void sse_encode_read_limits(ReadLimits self, SseSerializer serializer);

  @protected
  void sse_encode_read_start(ReadStart self, SseSerializer serializer);

  @protected
  void sse_encode_read_stop(ReadStop self, SseSerializer serializer);

  @protected
  void sse_encode_read_write_permissions(
    ReadWritePermissions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reconfigure_basin_input(
    ReconfigureBasinInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_list_prim_u_8_strict_list_prim_u_8_strict(
    (Uint8List, Uint8List) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resource_set(ResourceSet self, SseSerializer serializer);

  @protected
  void sse_encode_retention_policy(
    RetentionPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_retry_config(RetryConfig self, SseSerializer serializer);

  @protected
  void sse_encode_s_2_error(S2Error self, SseSerializer serializer);

  @protected
  void sse_encode_sequenced_record(
    SequencedRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_storage_class(StorageClass self, SseSerializer serializer);

  @protected
  void sse_encode_stream_config(StreamConfig self, SseSerializer serializer);

  @protected
  void sse_encode_stream_info(StreamInfo self, SseSerializer serializer);

  @protected
  void sse_encode_stream_position(
    StreamPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timestamping_config(
    TimestampingConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timestamping_mode(
    TimestampingMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    int ptr,
  );
}
