// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'append_session.dart';
import 'basin.dart';
import 'client.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'producer.dart';
import 'stream.dart';
import 'types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BatchSubmitTicketPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicketPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RecordSubmitTicketPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicketPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2AppendSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSessionPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2BasinPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2BasinPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2ClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ClientPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2ProducerPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ProducerPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_S2StreamPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2StreamPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  BatchSubmitTicket
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    dynamic raw,
  );

  @protected
  RecordSubmitTicket
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    dynamic raw,
  );

  @protected
  S2AppendSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    dynamic raw,
  );

  @protected
  S2Basin
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    dynamic raw,
  );

  @protected
  S2Client
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    dynamic raw,
  );

  @protected
  S2Producer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    dynamic raw,
  );

  @protected
  S2Stream
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    dynamic raw,
  );

  @protected
  S2AppendSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    dynamic raw,
  );

  @protected
  S2Basin
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    dynamic raw,
  );

  @protected
  S2Client
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    dynamic raw,
  );

  @protected
  S2Producer
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    dynamic raw,
  );

  @protected
  S2Stream
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    dynamic raw,
  );

  @protected
  BatchSubmitTicket
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    dynamic raw,
  );

  @protected
  RecordSubmitTicket
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    dynamic raw,
  );

  @protected
  S2AppendSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    dynamic raw,
  );

  @protected
  S2Basin
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    dynamic raw,
  );

  @protected
  S2Client
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    dynamic raw,
  );

  @protected
  S2Producer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    dynamic raw,
  );

  @protected
  S2Stream
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    dynamic raw,
  );

  @protected
  RustStreamSink<SequencedRecord> dco_decode_StreamSink_sequenced_record_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppendAck dco_decode_append_ack(dynamic raw);

  @protected
  AppendInput dco_decode_append_input(dynamic raw);

  @protected
  AppendRecord dco_decode_append_record(dynamic raw);

  @protected
  AppendRecordBatch dco_decode_append_record_batch(dynamic raw);

  @protected
  AppendRetryPolicy dco_decode_append_retry_policy(dynamic raw);

  @protected
  AppendSessionConfig dco_decode_append_session_config(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppendInput dco_decode_box_autoadd_append_input(dynamic raw);

  @protected
  AppendRecord dco_decode_box_autoadd_append_record(dynamic raw);

  @protected
  AppendRetryPolicy dco_decode_box_autoadd_append_retry_policy(dynamic raw);

  @protected
  AppendSessionConfig dco_decode_box_autoadd_append_session_config(dynamic raw);

  @protected
  ClientConfig dco_decode_box_autoadd_client_config(dynamic raw);

  @protected
  Compression dco_decode_box_autoadd_compression(dynamic raw);

  @protected
  ReadInput dco_decode_box_autoadd_read_input(dynamic raw);

  @protected
  RetryConfig dco_decode_box_autoadd_retry_config(dynamic raw);

  @protected
  StreamPosition dco_decode_box_autoadd_stream_position(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  ClientConfig dco_decode_client_config(dynamic raw);

  @protected
  Compression dco_decode_compression(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IndexedAppendAck dco_decode_indexed_append_ack(dynamic raw);

  @protected
  List<AppendRecord> dco_decode_list_append_record(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(Uint8List, Uint8List)>
  dco_decode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SequencedRecord> dco_decode_list_sequenced_record(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AppendRetryPolicy? dco_decode_opt_box_autoadd_append_retry_policy(
    dynamic raw,
  );

  @protected
  Compression? dco_decode_opt_box_autoadd_compression(dynamic raw);

  @protected
  RetryConfig? dco_decode_opt_box_autoadd_retry_config(dynamic raw);

  @protected
  StreamPosition? dco_decode_opt_box_autoadd_stream_position(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  ReadBatch dco_decode_read_batch(dynamic raw);

  @protected
  ReadFrom dco_decode_read_from(dynamic raw);

  @protected
  ReadInput dco_decode_read_input(dynamic raw);

  @protected
  ReadLimits dco_decode_read_limits(dynamic raw);

  @protected
  ReadStart dco_decode_read_start(dynamic raw);

  @protected
  ReadStop dco_decode_read_stop(dynamic raw);

  @protected
  (Uint8List, Uint8List)
  dco_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(dynamic raw);

  @protected
  RetryConfig dco_decode_retry_config(dynamic raw);

  @protected
  S2Error dco_decode_s_2_error(dynamic raw);

  @protected
  SequencedRecord dco_decode_sequenced_record(dynamic raw);

  @protected
  StreamPosition dco_decode_stream_position(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  BatchSubmitTicket
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    SseDeserializer deserializer,
  );

  @protected
  RecordSubmitTicket
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    SseDeserializer deserializer,
  );

  @protected
  S2AppendSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    SseDeserializer deserializer,
  );

  @protected
  S2Basin
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    SseDeserializer deserializer,
  );

  @protected
  S2Client
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    SseDeserializer deserializer,
  );

  @protected
  S2Producer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    SseDeserializer deserializer,
  );

  @protected
  S2Stream
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    SseDeserializer deserializer,
  );

  @protected
  S2AppendSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    SseDeserializer deserializer,
  );

  @protected
  S2Basin
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    SseDeserializer deserializer,
  );

  @protected
  S2Client
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    SseDeserializer deserializer,
  );

  @protected
  S2Producer
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    SseDeserializer deserializer,
  );

  @protected
  S2Stream
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    SseDeserializer deserializer,
  );

  @protected
  BatchSubmitTicket
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    SseDeserializer deserializer,
  );

  @protected
  RecordSubmitTicket
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    SseDeserializer deserializer,
  );

  @protected
  S2AppendSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    SseDeserializer deserializer,
  );

  @protected
  S2Basin
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    SseDeserializer deserializer,
  );

  @protected
  S2Client
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    SseDeserializer deserializer,
  );

  @protected
  S2Producer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    SseDeserializer deserializer,
  );

  @protected
  S2Stream
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SequencedRecord> sse_decode_StreamSink_sequenced_record_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppendAck sse_decode_append_ack(SseDeserializer deserializer);

  @protected
  AppendInput sse_decode_append_input(SseDeserializer deserializer);

  @protected
  AppendRecord sse_decode_append_record(SseDeserializer deserializer);

  @protected
  AppendRecordBatch sse_decode_append_record_batch(
    SseDeserializer deserializer,
  );

  @protected
  AppendRetryPolicy sse_decode_append_retry_policy(
    SseDeserializer deserializer,
  );

  @protected
  AppendSessionConfig sse_decode_append_session_config(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppendInput sse_decode_box_autoadd_append_input(SseDeserializer deserializer);

  @protected
  AppendRecord sse_decode_box_autoadd_append_record(
    SseDeserializer deserializer,
  );

  @protected
  AppendRetryPolicy sse_decode_box_autoadd_append_retry_policy(
    SseDeserializer deserializer,
  );

  @protected
  AppendSessionConfig sse_decode_box_autoadd_append_session_config(
    SseDeserializer deserializer,
  );

  @protected
  ClientConfig sse_decode_box_autoadd_client_config(
    SseDeserializer deserializer,
  );

  @protected
  Compression sse_decode_box_autoadd_compression(SseDeserializer deserializer);

  @protected
  ReadInput sse_decode_box_autoadd_read_input(SseDeserializer deserializer);

  @protected
  RetryConfig sse_decode_box_autoadd_retry_config(SseDeserializer deserializer);

  @protected
  StreamPosition sse_decode_box_autoadd_stream_position(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  ClientConfig sse_decode_client_config(SseDeserializer deserializer);

  @protected
  Compression sse_decode_compression(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IndexedAppendAck sse_decode_indexed_append_ack(SseDeserializer deserializer);

  @protected
  List<AppendRecord> sse_decode_list_append_record(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(Uint8List, Uint8List)>
  sse_decode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<SequencedRecord> sse_decode_list_sequenced_record(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AppendRetryPolicy? sse_decode_opt_box_autoadd_append_retry_policy(
    SseDeserializer deserializer,
  );

  @protected
  Compression? sse_decode_opt_box_autoadd_compression(
    SseDeserializer deserializer,
  );

  @protected
  RetryConfig? sse_decode_opt_box_autoadd_retry_config(
    SseDeserializer deserializer,
  );

  @protected
  StreamPosition? sse_decode_opt_box_autoadd_stream_position(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  ReadBatch sse_decode_read_batch(SseDeserializer deserializer);

  @protected
  ReadFrom sse_decode_read_from(SseDeserializer deserializer);

  @protected
  ReadInput sse_decode_read_input(SseDeserializer deserializer);

  @protected
  ReadLimits sse_decode_read_limits(SseDeserializer deserializer);

  @protected
  ReadStart sse_decode_read_start(SseDeserializer deserializer);

  @protected
  ReadStop sse_decode_read_stop(SseDeserializer deserializer);

  @protected
  (Uint8List, Uint8List)
  sse_decode_record_list_prim_u_8_strict_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  RetryConfig sse_decode_retry_config(SseDeserializer deserializer);

  @protected
  S2Error sse_decode_s_2_error(SseDeserializer deserializer);

  @protected
  SequencedRecord sse_decode_sequenced_record(SseDeserializer deserializer);

  @protected
  StreamPosition sse_decode_stream_position(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    BatchSubmitTicket self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    RecordSubmitTicket self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    S2AppendSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    S2Basin self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    S2Client self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    S2Producer self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    S2Stream self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    S2AppendSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    S2Basin self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    S2Client self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    S2Producer self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    S2Stream self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    BatchSubmitTicket self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    RecordSubmitTicket self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    S2AppendSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    S2Basin self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    S2Client self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    S2Producer self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    S2Stream self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sequenced_record_Sse(
    RustStreamSink<SequencedRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_append_ack(AppendAck self, SseSerializer serializer);

  @protected
  void sse_encode_append_input(AppendInput self, SseSerializer serializer);

  @protected
  void sse_encode_append_record(AppendRecord self, SseSerializer serializer);

  @protected
  void sse_encode_append_record_batch(
    AppendRecordBatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_append_retry_policy(
    AppendRetryPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_append_session_config(
    AppendSessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_append_input(
    AppendInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_append_record(
    AppendRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_append_retry_policy(
    AppendRetryPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_append_session_config(
    AppendSessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_client_config(
    ClientConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_compression(
    Compression self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_read_input(
    ReadInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_retry_config(
    RetryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stream_position(
    StreamPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_client_config(ClientConfig self, SseSerializer serializer);

  @protected
  void sse_encode_compression(Compression self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_indexed_append_ack(
    IndexedAppendAck self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_append_record(
    List<AppendRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_list_prim_u_8_strict_list_prim_u_8_strict(
    List<(Uint8List, Uint8List)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sequenced_record(
    List<SequencedRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_append_retry_policy(
    AppendRetryPolicy? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_compression(
    Compression? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_retry_config(
    RetryConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stream_position(
    StreamPosition? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_read_batch(ReadBatch self, SseSerializer serializer);

  @protected
  void sse_encode_read_from(ReadFrom self, SseSerializer serializer);

  @protected
  void sse_encode_read_input(ReadInput self, SseSerializer serializer);

  @protected
  void sse_encode_read_limits(ReadLimits self, SseSerializer serializer);

  @protected
  void sse_encode_read_start(ReadStart self, SseSerializer serializer);

  @protected
  void sse_encode_read_stop(ReadStop self, SseSerializer serializer);

  @protected
  void sse_encode_record_list_prim_u_8_strict_list_prim_u_8_strict(
    (Uint8List, Uint8List) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_retry_config(RetryConfig self, SseSerializer serializer);

  @protected
  void sse_encode_s_2_error(S2Error self, SseSerializer serializer);

  @protected
  void sse_encode_sequenced_record(
    SequencedRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stream_position(
    StreamPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicketPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicketPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicketPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicket =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatchSubmitTicketPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicketPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicketPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicketPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicket =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRecordSubmitTicketPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2AppendSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2BasinPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2BasinPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2BasinPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Basin =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2BasinPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Client =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ProducerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ProducerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ProducerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Producer =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2ProducerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2StreamPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2StreamPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2StreamPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_s2_sdk_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2Stream =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerS2StreamPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
