// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecordSubmitTicket>>
abstract class RecordSubmitTicket implements RustOpaqueInterface {
  Future<IndexedAppendAck> ack();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<S2Producer>>
abstract class S2Producer implements RustOpaqueInterface {
  Future<void> close();

  Future<RecordSubmitTicket> submit({required AppendRecord record});
}

class IndexedAppendAck {
  final BigInt seqNum;
  final AppendAck batch;

  const IndexedAppendAck({required this.seqNum, required this.batch});

  @override
  int get hashCode => seqNum.hashCode ^ batch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexedAppendAck &&
          runtimeType == other.runtimeType &&
          seqNum == other.seqNum &&
          batch == other.batch;
}
