// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'append_session.dart';
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'producer.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `try_into_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<S2Stream>>
abstract class S2Stream implements RustOpaqueInterface {
  Future<AppendAck> append({required AppendInput input});

  Future<S2AppendSession> appendSession({required AppendSessionConfig config});

  Future<StreamPosition> checkTail();

  Future<S2Producer> producer();

  Future<ReadBatch> read({required ReadInput input});

  Future<Stream<SequencedRecord>> readSession({required ReadInput input});
}

class AppendSessionConfig {
  final int? maxUnackedBytes;
  final int? maxUnackedBatches;

  const AppendSessionConfig({this.maxUnackedBytes, this.maxUnackedBatches});

  @override
  int get hashCode => maxUnackedBytes.hashCode ^ maxUnackedBatches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppendSessionConfig &&
          runtimeType == other.runtimeType &&
          maxUnackedBytes == other.maxUnackedBytes &&
          maxUnackedBatches == other.maxUnackedBatches;
}
