// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'append_session.dart';
import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'producer.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IStream>>
abstract class IStream implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<S2Stream>>
abstract class S2Stream implements RustOpaqueInterface {
  Future<AppendAck> append({required AppendInput input});

  Future<S2AppendSession> appendSession();

  Future<StreamPosition> checkTail();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<S2Stream> newInstance({required IStream stream}) =>
      RustLib.instance.api.crateStreamS2StreamNew(stream: stream);

  Future<S2Producer> producer();

  Future<ReadBatch> read({required ReadInput input});

  Stream<SequencedRecord> readSession({required ReadInput input});
}
