// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class AppendAck {
  final StreamPosition start;
  final StreamPosition end;
  final StreamPosition tail;

  const AppendAck({required this.start, required this.end, required this.tail});

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ tail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppendAck &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          tail == other.tail;
}

class AppendInput {
  final AppendRecordBatch records;
  final BigInt? matchSeqNum;
  final String? fencingToken;

  const AppendInput({
    required this.records,
    this.matchSeqNum,
    this.fencingToken,
  });

  @override
  int get hashCode =>
      records.hashCode ^ matchSeqNum.hashCode ^ fencingToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppendInput &&
          runtimeType == other.runtimeType &&
          records == other.records &&
          matchSeqNum == other.matchSeqNum &&
          fencingToken == other.fencingToken;
}

class AppendRecord {
  final Uint8List body;
  final List<(Uint8List, Uint8List)> headers;
  final BigInt? timestamp;

  const AppendRecord({
    required this.body,
    required this.headers,
    this.timestamp,
  });

  @override
  int get hashCode => body.hashCode ^ headers.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppendRecord &&
          runtimeType == other.runtimeType &&
          body == other.body &&
          headers == other.headers &&
          timestamp == other.timestamp;
}

class AppendRecordBatch {
  final List<AppendRecord> records;

  const AppendRecordBatch({required this.records});

  @override
  int get hashCode => records.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppendRecordBatch &&
          runtimeType == other.runtimeType &&
          records == other.records;
}

enum AppendRetryPolicy { all, noSideEffects }

class ClientConfig {
  final String accessToken;
  final String? endpoint;
  final BigInt? connectionTimeoutMillis;
  final BigInt? requestTimeoutMillis;
  final Compression? compression;
  final RetryConfig? retryConfig;

  const ClientConfig({
    required this.accessToken,
    this.endpoint,
    this.connectionTimeoutMillis,
    this.requestTimeoutMillis,
    this.compression,
    this.retryConfig,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^
      endpoint.hashCode ^
      connectionTimeoutMillis.hashCode ^
      requestTimeoutMillis.hashCode ^
      compression.hashCode ^
      retryConfig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientConfig &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          endpoint == other.endpoint &&
          connectionTimeoutMillis == other.connectionTimeoutMillis &&
          requestTimeoutMillis == other.requestTimeoutMillis &&
          compression == other.compression &&
          retryConfig == other.retryConfig;
}

enum Compression { none, gzip, zstd }

enum Operation {
  listBasins,
  createBasin,
  getBasinConfig,
  deleteBasin,
  reconfigureBasin,
  listAccessTokens,
  issueAccessToken,
  revokeAccessToken,
  getAccountMetrics,
  getBasinMetrics,
  getStreamMetrics,
  listStreams,
  createStream,
  getStreamConfig,
  deleteStream,
  reconfigureStream,
  checkTail,
  append,
  read,
  trim,
  fence,
}

class ReadBatch {
  final List<SequencedRecord> records;
  final StreamPosition? tail;

  const ReadBatch({required this.records, this.tail});

  @override
  int get hashCode => records.hashCode ^ tail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadBatch &&
          runtimeType == other.runtimeType &&
          records == other.records &&
          tail == other.tail;
}

@freezed
sealed class ReadFrom with _$ReadFrom {
  const ReadFrom._();

  const factory ReadFrom.seqNum(BigInt field0) = ReadFrom_SeqNum;
  const factory ReadFrom.timestamp(BigInt field0) = ReadFrom_Timestamp;
  const factory ReadFrom.tailOffset(BigInt field0) = ReadFrom_TailOffset;
}

class ReadInput {
  final ReadStart start;
  final ReadStop stop;

  const ReadInput({required this.start, required this.stop});

  @override
  int get hashCode => start.hashCode ^ stop.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadInput &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          stop == other.stop;
}

class ReadLimits {
  final BigInt? count;
  final BigInt? bytes;

  const ReadLimits({this.count, this.bytes});

  @override
  int get hashCode => count.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadLimits &&
          runtimeType == other.runtimeType &&
          count == other.count &&
          bytes == other.bytes;
}

class ReadStart {
  final ReadFrom from;
  final bool clampToTail;

  const ReadStart({required this.from, required this.clampToTail});

  @override
  int get hashCode => from.hashCode ^ clampToTail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadStart &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          clampToTail == other.clampToTail;
}

class ReadStop {
  final ReadLimits limits;
  final BigInt? untilTimestamp;
  final int? waitSecs;

  const ReadStop({required this.limits, this.untilTimestamp, this.waitSecs});

  @override
  int get hashCode =>
      limits.hashCode ^ untilTimestamp.hashCode ^ waitSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadStop &&
          runtimeType == other.runtimeType &&
          limits == other.limits &&
          untilTimestamp == other.untilTimestamp &&
          waitSecs == other.waitSecs;
}

@freezed
sealed class ResourceSet with _$ResourceSet {
  const ResourceSet._();

  const factory ResourceSet.none() = ResourceSet_None;
  const factory ResourceSet.exact(String field0) = ResourceSet_Exact;
  const factory ResourceSet.prefix(String field0) = ResourceSet_Prefix;
}

class RetryConfig {
  final int? maxAttempts;
  final BigInt? minBaseDelayMillis;
  final BigInt? maxBaseDelayMillis;
  final AppendRetryPolicy? appendRetryPolicy;

  const RetryConfig({
    this.maxAttempts,
    this.minBaseDelayMillis,
    this.maxBaseDelayMillis,
    this.appendRetryPolicy,
  });

  @override
  int get hashCode =>
      maxAttempts.hashCode ^
      minBaseDelayMillis.hashCode ^
      maxBaseDelayMillis.hashCode ^
      appendRetryPolicy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetryConfig &&
          runtimeType == other.runtimeType &&
          maxAttempts == other.maxAttempts &&
          minBaseDelayMillis == other.minBaseDelayMillis &&
          maxBaseDelayMillis == other.maxBaseDelayMillis &&
          appendRetryPolicy == other.appendRetryPolicy;
}

class SequencedRecord {
  final BigInt seqNum;
  final Uint8List body;
  final List<(Uint8List, Uint8List)> headers;
  final BigInt timestamp;

  const SequencedRecord({
    required this.seqNum,
    required this.body,
    required this.headers,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      seqNum.hashCode ^ body.hashCode ^ headers.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SequencedRecord &&
          runtimeType == other.runtimeType &&
          seqNum == other.seqNum &&
          body == other.body &&
          headers == other.headers &&
          timestamp == other.timestamp;
}

class StreamPosition {
  final BigInt seqNum;
  final BigInt timestamp;

  const StreamPosition({required this.seqNum, required this.timestamp});

  @override
  int get hashCode => seqNum.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamPosition &&
          runtimeType == other.runtimeType &&
          seqNum == other.seqNum &&
          timestamp == other.timestamp;
}
